"""Tests du client Polymarket (lecture seule).

Hors-ligne : un faux ``requests.Session`` rejoue des réponses calquées sur de vraies
réponses gamma / CLOB / data-api (septembre 2026). Les tests ``@pytest.mark.network``
interrogent les vraies API publiques.
"""

from __future__ import annotations

import copy
import json
import math
import threading
import time

import numpy as np
import pandas as pd
import pytest
import requests

from tradebot import polymarket as pm
from tradebot.polymarket import (
    ASSET_TO_SYMBOL,
    DURATION_SECONDS,
    PolymarketClient,
    PolymarketError,
    RateLimiter,
    UpDownMarket,
    markets_to_frame,
    slot_starts,
    taker_fee,
    up_price_at,
    updown_slug,
)

UTC = "UTC"

# ---------------------------------------------------------------------------
# Fixtures calquées sur de vraies réponses (btc-updown-15m-1790268300, résolu Down)
# ---------------------------------------------------------------------------
REAL_MARKET = {
    "id": "4884441",
    "question": "Bitcoin Up or Down - September 24, 12:45PM-1:00PM ET",
    "conditionId": "0x06fb249d000a806114a16116b76736e8233bf5444848718c172826b955f05cf1",
    "slug": "btc-updown-15m-1790268300",
    "resolutionSource": "https://data.chain.link/streams/btc-usd-twap-60s-streams",
    "endDate": "2026-09-24T17:00:00Z",
    "startDate": "2026-09-23T16:53:48.972999Z",
    "description": (
        'This market will resolve to "Up" if the time-weighted average price (TWAP) of Bitcoin, '
        "generated by Chainlink, of the time range specified in the title is greater than or equal "
        'to the price at the beginning of that range. Otherwise, it will resolve to "Down".'
    ),
    "image": "https://polymarket-upload.s3.us-east-2.amazonaws.com/BTC+fullsize.png",
    "icon": "https://polymarket-upload.s3.us-east-2.amazonaws.com/BTC+fullsize.png",
    "outcomes": '["Up", "Down"]',
    "outcomePrices": '["0", "1"]',
    "volume": "20330.50777699999",
    "active": True,
    "closed": True,
    "closedTime": "2026-09-24 17:00:53+00",
    "restricted": True,
    "questionID": "0xe209032de7f03f0be96f54b83100ef75fec75cc1cf3ff36d974e3795a9d6e39d",
    "umaEndDate": "2026-09-24T17:00:53Z",
    "enableOrderBook": True,
    "orderPriceMinTickSize": 0.001,
    "orderMinSize": 5,
    "umaResolutionStatus": "resolved",
    "umaResolutionStatuses": "[]",
    "volumeNum": 20330.50777699999,
    "clobTokenIds": (
        '["10150311971458959535499904846220561492823190034748085003302541825006000632797", '
        '"100740579834561810692759070795975566048563169342707868693516812615475245913895"]'
    ),
    "acceptingOrders": False,
    "negRisk": False,
    "spread": 0.001,
    "automaticallyResolved": True,
    "lastTradePrice": 0.001,
    "bestAsk": 0.001,
    "eventStartTime": "2026-09-24T16:45:00Z",
    "feesEnabled": True,
    "feeType": "crypto_fees_v2",
    "feeSchedule": {"exponent": 1, "rate": 0.07, "takerOnly": True, "rebateRate": 0.2},
    "cryptoMarketConfigId": "btc-15m-twap-60",
    "cryptoMarketConfig": {
        "id": "btc-15m-twap-60",
        "asset": "btc",
        "duration": "15m",
        "twapEnabled": True,
        "twapLookbackSeconds": 60,
    },
    "makerBaseFee": 1000,
    "takerBaseFee": 1000,
}

# Réponse réelle /book (bids croissants, asks décroissants : l'API renvoie le pire prix d'abord)
REAL_BOOK = {
    "market": "0x17fa5a62cca2910c5501aa09a4508dcc94bb9038c7c1f9229d5c2ba0464d951a",
    "asset_id": "25625480668105989920076375105881030556138325069313116095281856241367400404502",
    "timestamp": "1790354140125",
    "hash": "bcf04e86b5260f7bf21b39534f48cbee2ed50876",
    "bids": [
        {"price": "0.01", "size": "1699"},
        {"price": "0.12", "size": "1024.34"},
        {"price": "0.13", "size": "803.51"},
        {"price": "0.14", "size": "110"},
    ],
    "asks": [
        {"price": "0.99", "size": "1359.67"},
        {"price": "0.17", "size": "9051.69"},
        {"price": "0.16", "size": "597"},
        {"price": "0.15", "size": "242.95"},
    ],
    "min_order_size": "5",
    "tick_size": "0.01",
    "neg_risk": False,
    "last_trade_price": "0.150",
}

REAL_TRADE = {
    "proxyWallet": "0xbb0d358a5962840f5fc2ef3534383db1b49e54f9",
    "side": "SELL",
    "asset": "47662768722602004206787688604910020467295900128957367009461306675455542908485",
    "conditionId": "0x60292576f23d12de4d18c88af7700f7e157cc87c0ba2ae2a8f34285e9f68940a",
    "size": 5.35,
    "price": 0.999,
    "timestamp": 1790351129,
    "title": "Bitcoin Up or Down - September 25, 11:30AM-11:45AM ET",
    "slug": "btc-updown-15m-1790350200",
    "eventSlug": "btc-updown-15m-1790350200",
    "outcome": "Down",
    "outcomeIndex": 1,
    "name": "dasnew",
    "pseudonym": "Nifty-Short",
    "transactionHash": "0xdd886ebced4a23b7c9d72c2cc3b2bb4c25d6499aea84a9e05aaf57847942fe13",
}


def _iso(ts: int) -> str:
    return pd.Timestamp(ts, unit="s", tz=UTC).strftime("%Y-%m-%dT%H:%M:%SZ")


def make_market(
    start_ts: int, asset: str = "btc", duration: str = "15m", state: str = "up", end_ts: int | None = None
) -> dict:
    """Marché gamma réaliste. ``state`` : "up" | "down" (résolus), "open", "pending" (clos non résolu)."""
    m = copy.deepcopy(REAL_MARKET)
    end_ts = end_ts or start_ts + DURATION_SECONDS[duration]
    slug = f"{asset}-updown-{duration}-{start_ts}"
    up_tok, down_tok = str(10**70 + start_ts), str(2 * 10**70 + start_ts)
    m.update(
        {
            "slug": slug,
            "conditionId": "0x%064x" % start_ts,
            "eventStartTime": _iso(start_ts),
            "endDate": _iso(end_ts),
            "clobTokenIds": json.dumps([up_tok, down_tok]),
            "cryptoMarketConfig": {
                "id": f"{asset}-{duration}-twap-60",
                "asset": asset,
                "duration": duration,
                "twapEnabled": True,
                "twapLookbackSeconds": 60,
            },
        }
    )
    if state == "up":
        m["outcomePrices"] = '["1", "0"]'
    elif state == "down":
        m["outcomePrices"] = '["0", "1"]'
    else:
        m.update(
            {
                "closed": state == "pending",
                "acceptingOrders": state == "open",
                "umaResolutionStatus": None,
                "outcomePrices": '["0.485", "0.515"]',
                "bestBid": 0.46,
                "bestAsk": 0.47,
                "spread": 0.01,
                "liquidity": "16559.7254",
                "liquidityNum": 16559.7254,
            }
        )
    return m


def make_event(market: dict) -> dict:
    return {
        "id": "1069946",
        "ticker": market["slug"],
        "slug": market["slug"],
        "title": market["question"],
        "endDate": market["endDate"],
        "closed": market["closed"],
        "restricted": True,
        "markets": [market],
        "series": [{"id": "10192", "slug": "btc-up-or-down-15m", "recurrence": "15m"}],
    }


class FakeResponse:
    def __init__(self, status_code: int = 200, payload=None, headers=None):
        self.status_code = status_code
        self._payload = payload
        self.headers = headers or {}
        self.text = json.dumps(payload) if payload is not None else ""

    def json(self):
        if self._payload is None:
            raise ValueError("pas de JSON")
        return self._payload


def _items(params):
    if params is None:
        return []
    return list(params.items()) if isinstance(params, dict) else list(params)


class FakeSession:
    """Routeur minimal gamma / CLOB / data-api ; enregistre les appels."""

    def __init__(self, events=(), prices=None, books=None, trades=None, script=None):
        self.events = {e["slug"]: e for e in events}
        self.prices = prices or {}      # token -> [(t, p)]
        self.books = books or {}        # token -> payload
        self.trades = trades or {}      # condition_id -> [rows]
        self.script = list(script or [])  # réponses / exceptions imposées, consommées d'abord
        self.calls: list[tuple[str, list]] = []
        self.lock = threading.Lock()

    def count(self, fragment: str) -> int:
        return sum(fragment in url for url, _ in self.calls)

    def get(self, url, params=None, timeout=None):
        with self.lock:
            self.calls.append((url, _items(params)))
            if self.script:
                item = self.script.pop(0)
                if isinstance(item, Exception):
                    raise item
                return item
        p = _items(params)
        d = dict(p)
        if url.endswith("/events"):
            slugs = [v for k, v in p if k == "slug"]
            limit = int(d.get("limit", 20))
            return FakeResponse(200, [self.events[s] for s in slugs if s in self.events][:limit])
        if url.endswith("/prices-history"):
            pts = self.prices.get(d["market"], [])
            a, b = int(d["startTs"]), int(d["endTs"])
            return FakeResponse(200, {"history": [{"t": t, "p": v} for t, v in pts if a <= t <= b]})
        if url.endswith("/book"):
            tok = d["token_id"]
            if tok in self.books:
                return FakeResponse(200, self.books[tok])
            return FakeResponse(404, {"error": "No orderbook exists for the requested token id"})
        if url.endswith("/trades"):
            rows = self.trades.get(d["market"], [])
            off, lim = int(d.get("offset", 0)), int(d["limit"])
            return FakeResponse(200, rows[off : off + lim])
        return FakeResponse(404, {"error": "not found"})


class ExplodingSession:
    """Toute requête échoue : prouve qu'une donnée vient du cache."""

    def __init__(self):
        self.calls = 0

    def get(self, *a, **k):
        self.calls += 1
        raise AssertionError("appel réseau inattendu")


def client_for(session, tmp_path, **kw) -> PolymarketClient:
    kw.setdefault("max_rps", 1000.0)
    kw.setdefault("backoff", 0.0)
    return PolymarketClient(session=session, cache_dir=tmp_path / "pm", **kw)


def ts(s: str) -> int:
    return int(pd.Timestamp(s, tz=UTC).timestamp())


# ---------------------------------------------------------------------------
# Slugs et créneaux
# ---------------------------------------------------------------------------
def test_constants():
    assert ASSET_TO_SYMBOL == {
        "btc": "BTCUSDT", "eth": "ETHUSDT", "sol": "SOLUSDT",
        "xrp": "XRPUSDT", "bnb": "BNBUSDT", "doge": "DOGEUSDT",
    }
    assert DURATION_SECONDS == {"5m": 300, "15m": 900, "4h": 14400}


def test_updown_slug():
    assert updown_slug("btc", "15m", 1790268300) == "btc-updown-15m-1790268300"
    assert updown_slug("BTCUSDT", "5m", 1790352600) == "btc-updown-5m-1790352600"
    assert updown_slug("eth", "4h", 1768438800) == "eth-updown-4h-1768438800"
    with pytest.raises(ValueError):
        updown_slug("btc", "1h", 1790268300)
    with pytest.raises(ValueError):
        updown_slug("btc", "15m", 1790268301)  # non aligné
    assert pm.parse_slug("sol-updown-5m-1790352600") == ("sol", "5m", 1790352600)
    with pytest.raises(ValueError):
        pm.parse_slug("bitcoin-up-or-down-september-25")


def test_slot_starts_5m_15m_half_open():
    s = slot_starts("15m", pd.Timestamp("2026-09-24 16:40", tz=UTC), pd.Timestamp("2026-09-24 17:30", tz=UTC))
    assert s == [ts("2026-09-24 16:45"), ts("2026-09-24 17:00"), ts("2026-09-24 17:15")]
    assert all(x % 900 == 0 for x in s)
    # bornes : début inclus, fin exclue ; entrées naïves = UTC
    s5 = slot_starts("5m", pd.Timestamp("2026-09-24 16:45"), pd.Timestamp("2026-09-24 17:00"))
    assert s5 == [ts("2026-09-24 16:45"), ts("2026-09-24 16:50"), ts("2026-09-24 16:55")]
    assert slot_starts("5m", pd.Timestamp("2026-09-24 17:00", tz=UTC), pd.Timestamp("2026-09-24 16:00", tz=UTC)) == []
    day = slot_starts("5m", pd.Timestamp("2026-09-24", tz=UTC), pd.Timestamp("2026-09-25", tz=UTC))
    assert len(day) == 288


def test_slot_starts_4h_new_york_alignment():
    """Vérifié sur l'API : 4h alignées sur New York (EDT -> 0h/4h… UTC ; EST -> 1h/5h… UTC)."""
    summer = slot_starts("4h", pd.Timestamp("2026-09-25", tz=UTC), pd.Timestamp("2026-09-26", tz=UTC))
    assert [pd.Timestamp(x, unit="s", tz=UTC).hour for x in summer] == [0, 4, 8, 12, 16, 20]
    assert all(x % 14400 == 0 for x in summer)
    winter = slot_starts("4h", pd.Timestamp("2026-01-15", tz=UTC), pd.Timestamp("2026-01-16", tz=UTC))
    assert [pd.Timestamp(x, unit="s", tz=UTC).hour for x in winter] == [1, 5, 9, 13, 17, 21]
    assert 1768438800 in winter  # btc-updown-4h-1768438800 existe (8:00PM-12:00AM ET)
    # passage à l'heure d'été (8 mars 2026) : 00h EST puis 04h EDT
    dst = slot_starts("4h", pd.Timestamp("2026-03-08", tz=UTC), pd.Timestamp("2026-03-09", tz=UTC))
    assert [pd.Timestamp(x, unit="s", tz=UTC).hour for x in dst] == [1, 5, 8, 12, 16, 20]
    for x in summer + winter + dst:
        assert pd.Timestamp(x, unit="s", tz=UTC).tz_convert("America/New_York").hour % 4 == 0


# ---------------------------------------------------------------------------
# Parsing
# ---------------------------------------------------------------------------
def test_parse_real_market_resolved_down():
    m = pm.parse_market(REAL_MARKET, make_event(REAL_MARKET))
    assert isinstance(m, UpDownMarket)
    assert (m.asset, m.duration, m.symbol) == ("btc", "15m", "BTCUSDT")
    assert m.start == pd.Timestamp("2026-09-24 16:45", tz=UTC)
    assert m.end - m.start == pd.Timedelta("15min")
    assert m.token_up.startswith("1015031197") and m.token_down.startswith("1007405798")
    assert m.closed and m.resolved_up is False and m.is_resolved
    assert m.outcome_prices == (0.0, 1.0)
    assert m.fee_schedule == {"exponent": 1, "rate": 0.07, "takerOnly": True, "rebateRate": 0.2}
    assert m.fee_type == "crypto_fees_v2"
    assert m.twap_lookback_s == 60 and m.resolution_rule == "twap"
    assert m.restricted and not m.accepting_orders
    assert math.isnan(m.best_bid) and m.best_ask == 0.001 and math.isnan(m.liquidity)
    assert m.volume == pytest.approx(20330.50777699999)
    assert "raw" not in repr(m) and "description" not in repr(m)


def test_parse_up_open_pending_and_reversed_outcomes():
    up = pm.parse_market(make_market(ts("2026-09-24 17:00"), state="up"))
    assert up.resolved_up is True and up.up_price == 1.0
    op = pm.parse_market(make_market(ts("2026-09-24 17:00"), state="open"))
    assert op.resolved_up is None and not op.closed and op.accepting_orders and not op.is_resolved
    assert op.outcome_prices == (0.485, 0.515) and op.liquidity == pytest.approx(16559.7254)
    pend = pm.parse_market(make_market(ts("2026-09-24 17:00"), state="pending"))
    assert pend.closed and pend.resolved_up is None and not pend.is_resolved
    # ordre des issues inversé : le mapping suit « outcomes », pas la position
    raw = make_market(ts("2026-09-24 17:00"), state="up")
    toks = json.loads(raw["clobTokenIds"])
    raw.update({"outcomes": '["Down", "Up"]', "outcomePrices": '["0", "1"]', "clobTokenIds": json.dumps(toks[::-1])})
    rev = pm.parse_market(raw)
    assert rev.resolved_up is True and rev.token_up == toks[0] and rev.token_down == toks[1]
    # ancien marché : pas de frais ni de TWAP
    old = make_market(ts("2025-12-15 12:00"), state="down")
    old.update({"feesEnabled": False, "feeSchedule": None, "feeType": None})
    old.pop("cryptoMarketConfig")
    o = pm.parse_market(old)
    assert o.fee_schedule is None and o.twap_lookback_s is None and o.resolution_rule == "last_price"
    assert (o.asset, o.duration) == ("btc", "15m")  # déduits du slug


# ---------------------------------------------------------------------------
# Client : marchés, 404, retentatives, cache
# ---------------------------------------------------------------------------
def test_get_updown_market_and_missing(tmp_path):
    start = ts("2026-09-24 16:45")
    sess = FakeSession(events=[make_event(REAL_MARKET)])
    c = client_for(sess, tmp_path)
    m = c.get_updown_market("btc", "15m", start)
    assert m is not None and m.slug == "btc-updown-15m-1790268300" and m.resolved_up is False
    # marché inexistant : l'API renvoie [] -> None
    assert c.get_updown_market("btc", "15m", start + 900) is None
    # 404 -> None
    c404 = client_for(FakeSession(script=[FakeResponse(404, {"error": "not found"})]), tmp_path / "x")
    assert c404.get_updown_market("eth", "5m", start) is None


def test_retries_then_success_and_exhaustion(tmp_path):
    start = ts("2026-09-24 16:45")
    sess = FakeSession(
        events=[make_event(REAL_MARKET)],
        script=[FakeResponse(503), requests.ConnectionError("reset"), FakeResponse(429, headers={"Retry-After": "0"})],
    )
    c = client_for(sess, tmp_path, use_cache=False)
    assert c.get_updown_market("btc", "15m", start) is not None
    assert len(sess.calls) == 4
    bad = FakeSession(script=[FakeResponse(500)] * 10)
    c2 = client_for(bad, tmp_path, retries=2, use_cache=False)
    with pytest.raises(PolymarketError):
        c2.get_updown_market("btc", "15m", start)
    assert len(bad.calls) == 3
    # 4xx autre que 404/429 : pas de retentative
    c3 = client_for(FakeSession(script=[FakeResponse(422, {"error": "validation"})]), tmp_path, use_cache=False)
    with pytest.raises(PolymarketError):
        c3.get_updown_market("btc", "15m", start)


def test_list_updown_markets_batches_and_caches_resolved(tmp_path):
    t0 = ts("2026-01-15 00:00")
    starts = [t0 + 900 * i for i in range(8)]
    events = [make_event(make_market(s, state="up" if i % 2 else "down")) for i, s in enumerate(starts[:6])]
    events.append(make_event(make_market(starts[6], state="pending")))  # clos, non résolu
    # starts[7] : créneau inexistant (ancien -> absence confirmée et mise en cache)
    sess = FakeSession(events=events)
    c = client_for(sess, tmp_path)
    ms = c.list_updown_markets("btc", "15m", pd.Timestamp("2026-01-15", tz=UTC), pd.Timestamp("2026-01-15 02:00", tz=UTC))
    assert [m.slug for m in ms] == [f"btc-updown-15m-{s}" for s in starts[:7]]
    assert sess.count("/events") == 1  # un seul appel groupé
    assert [m.resolved_up for m in ms[:6]] == [False, True, False, True, False, True]
    files = list((tmp_path / "pm" / "markets").glob("*.parquet"))
    assert [f.name for f in files] == ["btc_15m_2026-01.parquet"]

    # nouveau client, même cache : seul le marché non résolu est redemandé
    sess2 = FakeSession(events=events)
    c2 = client_for(sess2, tmp_path)
    ms2 = c2.list_updown_markets("btc", "15m", pd.Timestamp("2026-01-15", tz=UTC), pd.Timestamp("2026-01-15 02:00", tz=UTC))
    assert [m.slug for m in ms2] == [m.slug for m in ms]
    assert sess2.count("/events") == 1
    asked = [v for k, v in sess2.calls[0][1] if k == "slug"]
    assert asked == [f"btc-updown-15m-{starts[6]}"]
    cached = ms2[0]
    assert cached.resolved_up is False and cached.fee_schedule["rate"] == 0.07
    assert "description" not in cached.raw  # champs volumineux retirés du cache

    # only_closed
    closed = c2.list_updown_markets(
        "btc", "15m", pd.Timestamp("2026-01-15", tz=UTC), pd.Timestamp("2026-01-15 02:00", tz=UTC), only_closed=True
    )
    assert len(closed) == 7


def test_cache_merges_writes_from_two_clients(tmp_path):
    x, y = ts("2026-01-20 10:00"), ts("2026-01-20 10:15")
    c1 = client_for(FakeSession(events=[make_event(make_market(x, state="up"))]), tmp_path)
    c2 = client_for(FakeSession(events=[make_event(make_market(y, state="down"))]), tmp_path)
    c2._load_month("btc", "15m", "2026-01")  # c2 a déjà une vue (vide) du mois
    assert c1.get_updown_market("btc", "15m", x).resolved_up is True
    assert c2.get_updown_market("btc", "15m", y).resolved_up is False
    c3 = client_for(ExplodingSession(), tmp_path)
    assert c3.get_updown_market("btc", "15m", x).resolved_up is True
    assert c3.get_updown_market("btc", "15m", y).resolved_up is False


def test_list_updown_markets_parallel_batches(tmp_path):
    t0 = ts("2026-02-01 00:00")
    starts = [t0 + 300 * i for i in range(120)]  # 120 créneaux -> 3 lots de 50
    sess = FakeSession(events=[make_event(make_market(s, duration="5m")) for s in starts])
    c = client_for(sess, tmp_path)
    ms = c.list_updown_markets("btc", "5m", pd.Timestamp(t0, unit="s", tz=UTC),
                               pd.Timestamp(t0 + 300 * 120, unit="s", tz=UTC), max_workers=3)
    assert len(ms) == 120 and sess.count("/events") == 3
    assert all(len([1 for k, _ in p if k == "slug"]) <= pm.GAMMA_BATCH for _, p in sess.calls)
    assert [m.start for m in ms] == sorted(m.start for m in ms)


def test_recent_missing_slot_is_not_cached(tmp_path):
    now = pd.Timestamp.now(tz=UTC)
    sess = FakeSession()
    c = client_for(sess, tmp_path)
    s = slot_starts("15m", now - pd.Timedelta("30min"), now + pd.Timedelta("1h"))
    assert c.list_updown_markets("btc", "15m", now - pd.Timedelta("30min"), now + pd.Timedelta("1h")) == []
    assert not list((tmp_path / "pm").rglob("*.parquet"))
    c.list_updown_markets("btc", "15m", now - pd.Timedelta("30min"), now + pd.Timedelta("1h"))
    assert sess.count("/events") == 2 and len(s) > 0


def test_current_and_next_markets(tmp_path):
    now = pd.Timestamp("2026-09-25 16:37", tz=UTC)
    base = ts("2026-09-25 16:30")
    evs = [make_event(make_market(base + 900 * k, state="open")) for k in range(3)]
    c = client_for(FakeSession(events=evs), tmp_path)
    ms = c.current_and_next_markets("btc", "15m", now=now)
    assert [m.start for m in ms] == [pd.Timestamp(base + 900 * k, unit="s", tz=UTC) for k in range(3)]
    assert ms[0].start <= now < ms[0].end
    # 4h en hiver : fenêtre en cours = 20:00 ET = 01:00 UTC
    now4 = pd.Timestamp("2026-01-15 03:00", tz=UTC)
    s4 = [ts("2026-01-15 01:00"), ts("2026-01-15 05:00"), ts("2026-01-15 09:00")]
    ev4 = [make_event(make_market(s, duration="4h", state="open")) for s in s4]
    c4 = client_for(FakeSession(events=ev4), tmp_path)
    got = c4.current_and_next_markets("btc", "4h", now=now4)
    assert [int(m.start.timestamp()) for m in got] == s4


# ---------------------------------------------------------------------------
# Prix, carnet, transactions
# ---------------------------------------------------------------------------
def _history_points(start: int) -> list[tuple[int, float]]:
    """Profil réel : 0,505 avant l'ouverture, puis convergence vers 0 (résolu Down)."""
    before = [(start - 1780 + 60 * i, 0.505) for i in range(29)]
    during = [(start + 17, 0.545), (start + 76, 0.545), (start + 136, 0.605), (start + 314, 0.465),
              (start + 555, 0.145), (start + 735, 0.015), (start + 855, 0.0005), (start + 916, 0.0005)]
    return before + during


def test_prices_history_parsing_and_cache(tmp_path):
    start = ts("2026-09-24 16:45")
    tok_up = json.loads(REAL_MARKET["clobTokenIds"])[0]
    sess = FakeSession(events=[make_event(REAL_MARKET)], prices={tok_up: _history_points(start)})
    c = client_for(sess, tmp_path)
    m = c.get_updown_market("btc", "15m", start)
    h = c.prices_history(m.token_up, start - 1800, start + 1200)
    assert isinstance(h, pd.Series) and len(h) == 37
    assert str(h.index.tz) == "UTC" and h.index.is_monotonic_increasing
    assert h.iloc[0] == 0.505 and h.iloc[-1] == 0.0005
    assert sess.count("/prices-history") == 1
    # marché résolu -> relu depuis le disque, sans réseau
    c2 = client_for(ExplodingSession(), tmp_path)
    h2 = c2.prices_history(m.token_up, start - 1800, start + 1200, resolved=True)
    pd.testing.assert_series_equal(h, h2)


def test_prices_history_open_market_not_cached_and_chunked(tmp_path):
    now = int(time.time())
    start = now - now % 900
    raw = make_market(start, state="open")
    tok = json.loads(raw["clobTokenIds"])[0]
    pts = [(start - 60 * i, 0.5) for i in range(5)]
    sess = FakeSession(events=[make_event(raw)], prices={tok: pts})
    c = client_for(sess, tmp_path)
    c.current_and_next_markets("btc", "15m", n_next=0)
    c.prices_history(tok, start - 600, start + 60)
    c.prices_history(tok, start - 600, start + 60)
    assert sess.count("/prices-history") == 2
    assert not (tmp_path / "pm" / "prices").exists()
    # intervalle long découpé en tranches de 3 jours (l'API refuse 15 jours)
    c.prices_history(tok, start - 7 * 86400, start, resolved=False)
    assert sess.count("/prices-history") == 5


def test_up_price_at_staleness():
    idx = pd.to_datetime([ts("2026-09-24 16:44:15"), ts("2026-09-24 16:45:17"), ts("2026-09-24 16:46:16")], unit="s", utc=True)
    h = pd.Series([0.505, 0.545, 0.605], index=idx)
    assert math.isnan(up_price_at(h, pd.Timestamp("2026-09-24 16:44:00", tz=UTC)))  # avant le 1er point
    assert up_price_at(h, pd.Timestamp("2026-09-24 16:45:00", tz=UTC)) == 0.505
    assert up_price_at(h, pd.Timestamp("2026-09-24 16:45:17", tz=UTC)) == 0.545  # point exact inclus
    assert up_price_at(h, pd.Timestamp("2026-09-24 16:49:00", tz=UTC)) == 0.605
    assert math.isnan(up_price_at(h, pd.Timestamp("2026-09-24 16:49:30", tz=UTC)))  # > 3 min
    assert up_price_at(h, pd.Timestamp("2026-09-24 16:55", tz=UTC), max_staleness=pd.Timedelta("10min")) == 0.605
    assert up_price_at(h, pd.Timestamp("2026-09-24 16:45:30")) == 0.545  # naïf = UTC
    assert math.isnan(up_price_at(pd.Series(dtype=float), pd.Timestamp("2026-09-24", tz=UTC)))
    assert up_price_at(h.iloc[::-1], pd.Timestamp("2026-09-24 16:46:30", tz=UTC)) == 0.605  # non trié


def test_order_book_sorted_with_depth(tmp_path):
    tok = REAL_BOOK["asset_id"]
    c = client_for(FakeSession(books={tok: REAL_BOOK}), tmp_path)
    b = c.order_book(tok)
    assert b["exists"]
    assert [p for p, _ in b["bids"]] == [0.14, 0.13, 0.12, 0.01]
    assert [p for p, _ in b["asks"]] == [0.15, 0.16, 0.17, 0.99]
    assert (b["best_bid"], b["best_ask"]) == (0.14, 0.15)
    assert b["mid"] == pytest.approx(0.145) and b["spread"] == pytest.approx(0.01)
    # ±2 c autour de 0,145 : bids >= 0,125 (0,14 et 0,13), asks <= 0,165 (0,15 et 0,16)
    assert b["bid_depth_usd"] == pytest.approx(0.14 * 110 + 0.13 * 803.51)
    assert b["ask_depth_usd"] == pytest.approx(0.15 * 242.95 + 0.16 * 597)
    assert b["tick_size"] == 0.01 and b["min_order_size"] == 5 and b["last_trade_price"] == 0.15
    assert b["timestamp"] == pd.Timestamp(1790354140125, unit="ms", tz=UTC)
    # marché résolu : pas de carnet (404) -> carnet vide
    empty = c.order_book("123")
    assert not empty["exists"] and empty["bids"] == [] and math.isnan(empty["mid"])


def test_trades_frame_and_pagination(tmp_path):
    cid = REAL_TRADE["conditionId"]
    rows = []
    for i in range(1200):
        r = dict(REAL_TRADE, timestamp=REAL_TRADE["timestamp"] - i, price=0.5 + (i % 10) / 100, size=10.0)
        rows.append(r)
    sess = FakeSession(trades={cid: rows})
    c = client_for(sess, tmp_path)
    df = c.trades(cid, limit=1500)
    assert len(df) == 1200 and sess.count("/trades") == 3
    assert list(df.columns) == ["time", "side", "outcome", "outcome_index", "price", "size", "notional",
                                "asset", "wallet", "tx_hash"]
    assert str(df["time"].dt.tz) == "UTC"
    assert df.loc[0, "notional"] == pytest.approx(0.5 * 10.0)
    assert df.loc[0, "outcome"] == "Down" and df.loc[0, "side"] == "SELL"
    small = c.trades(cid, limit=20)
    assert len(small) == 20
    assert c.trades("0xabsent").empty


# ---------------------------------------------------------------------------
# Frais, cadre, limiteur
# ---------------------------------------------------------------------------
CRYPTO_V2 = {"exponent": 1, "rate": 0.07, "takerOnly": True, "rebateRate": 0.2}


@pytest.mark.parametrize(
    "price, expected_100_shares",
    # table officielle docs.polymarket.com/trading/fees (Crypto, 100 parts), arrondie au cent
    [(0.01, 0.07), (0.05, 0.33), (0.10, 0.63), (0.20, 1.12), (0.30, 1.47), (0.40, 1.68),
     (0.50, 1.75), (0.60, 1.68), (0.70, 1.47), (0.90, 0.63), (0.99, 0.07)],
)
def test_taker_fee_matches_official_table(price, expected_100_shares):
    assert round(taker_fee(price, 100, CRYPTO_V2), 2) == pytest.approx(expected_100_shares)


def test_taker_fee_exact_values_and_vectorized():
    assert taker_fee(0.5, 100, CRYPTO_V2) == pytest.approx(1.75)
    assert taker_fee(0.3, 100, CRYPTO_V2) == taker_fee(0.7, 100, CRYPTO_V2)  # symétrique
    assert taker_fee(0.5, 100, None) == 0.0
    # ancien barème crypto_fees (rate 0,25, exposant 2) : 1,5625 $ pour 100 parts à 0,50
    assert taker_fee(0.5, 100, {"rate": 0.25, "exponent": 2}) == pytest.approx(1.5625)
    arr = taker_fee(np.array([0.1, 0.5, 0.9]), np.array([10, 20, 30]), CRYPTO_V2)
    assert isinstance(arr, np.ndarray)
    np.testing.assert_allclose(arr, [0.063, 0.35, 0.189])
    # arrondi à 5 décimales (minimum 0,00001 USDC)
    assert taker_fee(0.001, 0.01, CRYPTO_V2) == 0.0
    assert taker_fee(0.5, 1, {"rate": "0.07", "exponent": 1}) == pytest.approx(0.0175)  # chaînes décimales
    assert math.isnan(taker_fee(1.2, 1, CRYPTO_V2))
    assert pm.breakeven_probability(0.5, CRYPTO_V2) == pytest.approx(0.5175)


def test_markets_to_frame(tmp_path):
    ms = [pm.parse_market(make_market(ts("2026-09-24 17:00"), state="up")),
          pm.parse_market(REAL_MARKET),
          pm.parse_market(make_market(ts("2026-09-24 17:15"), state="open"))]
    df = markets_to_frame(ms)
    assert len(df) == 3 and df["start"].is_monotonic_increasing
    assert str(df["start"].dt.tz) == "UTC"
    assert df["up_final"].tolist()[:2] == [0.0, 1.0] and math.isnan(df["up_final"].iloc[2])
    assert (df["symbol"] == "BTCUSDT").all() and (df["fee_rate"] == 0.07).all()
    assert (df["resolution_rule"] == "twap").all()
    empty = markets_to_frame([])
    assert empty.empty and "up_final" in empty.columns and str(empty["start"].dt.tz) == "UTC"


def test_rate_limiter_throttles_across_threads():
    rl = RateLimiter(rate=100.0, burst=1)
    t0 = time.monotonic()

    def work():
        for _ in range(5):
            rl.acquire()

    threads = [threading.Thread(target=work) for _ in range(4)]
    for t in threads:
        t.start()
    for t in threads:
        t.join()
    assert time.monotonic() - t0 >= 0.17  # 20 jetons à 100/s, 1 en rafale -> >= 0,19 s


def test_client_is_read_only():
    forbidden = ("post", "create_order", "place_order", "cancel", "sign", "private_key")
    names = [n.lower() for n in dir(PolymarketClient)]
    assert not [n for n in names if any(f in n for f in forbidden)]


# ---------------------------------------------------------------------------
# Tests réseau (vraies API publiques)
# ---------------------------------------------------------------------------
def _yesterday_15m() -> int:
    t = int(time.time()) - 86400
    return t - t % 900


@pytest.mark.network
def test_network_resolved_btc_15m_yesterday(tmp_path):
    c = PolymarketClient(cache_dir=tmp_path / "pm")
    m = c.get_updown_market("btc", "15m", _yesterday_15m())
    assert m is not None
    assert m.closed and m.resolved_up in (True, False) and m.is_resolved
    assert m.end - m.start == pd.Timedelta("15min")
    assert m.token_up and m.token_down and m.condition_id.startswith("0x")
    assert m.fee_schedule is not None and m.fee_schedule["rate"] > 0
    assert sorted(m.outcome_prices) == [0.0, 1.0]
    # historique de prix : non vide, dans [0, 1], converge vers l'issue
    start = int(m.start.timestamp())
    h = c.prices_history(m.token_up, start - 600, int(m.end.timestamp()) + 300)
    assert len(h) > 5 and h.between(0, 1).all()
    final = up_price_at(h, m.end + pd.Timedelta("2min"))
    assert abs(final - float(m.resolved_up)) < 0.1
    # transactions
    tr = c.trades(m.condition_id, limit=50)
    assert len(tr) > 0 and tr["price"].between(0, 1).all()


@pytest.mark.network
def test_network_list_and_cache(tmp_path):
    t0 = pd.Timestamp(_yesterday_15m(), unit="s", tz=UTC)
    c = PolymarketClient(cache_dir=tmp_path / "pm")
    ms = c.list_updown_markets("btc", "15m", t0, t0 + pd.Timedelta("2h"))
    assert len(ms) == 8 and all(m.is_resolved for m in ms)
    df = markets_to_frame(ms)
    assert df["up_final"].isin([0.0, 1.0]).all()
    c2 = PolymarketClient(session=ExplodingSession(), cache_dir=tmp_path / "pm")
    assert [m.slug for m in c2.list_updown_markets("btc", "15m", t0, t0 + pd.Timedelta("2h"))] == [m.slug for m in ms]


@pytest.mark.network
def test_network_current_market_order_book(tmp_path):
    c = PolymarketClient(cache_dir=tmp_path / "pm")
    now = pd.Timestamp.now(tz=UTC)
    ms = c.current_and_next_markets("btc", "15m")
    assert ms, "aucun marché BTC 15m en cours"
    assert ms[0].start <= now < ms[0].end and not ms[0].closed
    book = c.order_book(ms[0].token_up)
    assert book["exists"] and (book["bids"] or book["asks"])
    if book["bids"] and book["asks"]:
        assert book["best_bid"] < book["best_ask"]
    bids = [p for p, _ in book["bids"]]
    assert bids == sorted(bids, reverse=True)


@pytest.mark.network
def test_network_4h_alignment(tmp_path):
    c = PolymarketClient(cache_dir=tmp_path / "pm")
    ms = c.current_and_next_markets("eth", "4h", n_next=1)
    assert ms
    for m in ms:
        assert m.start.tz_convert("America/New_York").hour % 4 == 0
        assert m.end - m.start == pd.Timedelta("4h")
